### 
# == Halaman Cari - Search ==
GET http://localhost:5000/api/news/search?q=kampus
Content-Type: application/json

###
# == Halaman Magang ==
GET http://localhost:5000/api/news/magang/2
Content-Type: application/json


