###
# == Halaman Dashboard User
DELETE http://localhost:5000/api/public/dashboard/like/22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiVXNlcjEyMyIsImVtYWlsIjoiVXNlcjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3NDUzMzY2NDcsImV4cCI6MTc0NTMzNjY2N30.J9HuXNgzPwLSwca63s0gH7MTAURxZMrLvkZFPwIHFfQ
###
# == Halaman Dashboard User
GET http://localhost:5000/api/public/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiVXNlcjEyMyIsImVtYWlsIjoiVXNlcjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3NDUzMzY2NTgsImV4cCI6MTc0NTMzNjY3OH0.YXzLqJTy8gqfWp4_lW-GyCcmsRCiXHcrHJg6eXkTTDw

###
# Refresh Token 
GET http://localhost:5000/api/token
Content-Type: application/json

###
# Login Akun 
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "username" : "User123",
  "password" : "User123"
}

###
PUT http://localhost:5000/api/public/updateUserPublic
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiVXNlcjEyMyIsImVtYWlsIjoiVXNlcjEyM0BnbWFpbC5jb20iLCJpYXQiOjE3NDUzMzQ2NTQsImV4cCI6MTc0NTMzNDY3NH0.e9camfLs-Mr0POT3cuzuiUZByYGkFxuO7dUaqySeeBM

{
  "name" : "User",
  "username" : "User123",
  "email" : "User123@gmail.com",
  "password_lama": "User123",
  "password_baru": "User321"
}
