### Edit Akun
GET http://localhost:5000/api/public/dashboard
Content-Type: application/json
Authorization: Bereer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJ1c2VybmFtZSI6IldpamRhbjEyMyIsInJvbGUiOiJwdWJsaWMiLCJpYXQiOjE3NDU0Nzk3OTgsImV4cCI6MTc0NTQ3OTgxOH0.V41X57ln9ZF-3tN6XY766A0Vw9170nwt7Nf6HNQFwpE

###
# Refresh Token 
GET http://localhost:5000/api/token
Content-Type: application/json


###
# == Halaman Login ==
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username" : "Wijdan123",
  "password" : "Wijdan123"
}